export const SET_USER = 'SET_USER'
export const REGISTER = 'REGISTER'
export const LOG_IN = 'LOG_IN'
export const LOG_IN_WITH_GOOGLE = 'LOG_IN_WITH_GOOGLE'
export const LOG_OUT = 'LOG_OUT'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
